/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agf.sinalescolar.view;

import com.agf.sinalescolar.dao.OcorrenciaDAO;
import com.agf.sinalescolar.model.Ocorrencia;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Airan
 */
public class ifmOcorrencias extends javax.swing.JInternalFrame {
    private int idOcorrencia = 0;
    private final OcorrenciaDAO od = OcorrenciaDAO.getInstance();
    private Ocorrencia oSelecionada = null;

    /**
     * Creates new form ifmOcorrencias
     */
    public ifmOcorrencias() {
        initComponents();
        this.setSize(new Dimension(735, 495));
        atualizarTabela();
    }
    
    public void atualizarTabela() {
        od.popularTabelaOcorrencias(tblOcorrencias, "");
    }
    
    public void limparCampos() {
        
        idOcorrencia = 0;
        oSelecionada = null;
        tblOcorrencias.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
